apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: gcr.io/barnie/payment:v2beta2
          command:
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: payment-config
              mountPath: /go/bin/
              readOnly: true
      volumes:
        - name: payment-config
          configMap: { name: payment-config }
---
kind: Service
apiVersion: v1
metadata:
  name: payment-service
spec:
  type: LoadBalancer
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
