apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: gcr.io/barnie/payment
          command:
          ports:
            - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: payment-service
spec:
  type: LoadBalancer
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
